### PR TITLE
Bumped to C++23, Emscripten 3.1.47, UT v2.0.0 and added ImChart

### PR DESCRIPTION
**Pull request by RalphSteinhagen**
Pushed this already now because some of the commits might be useful for other PR in preparation (@ivan-cukic and @frankosterfeld emscripten version issues, @drslebedev signal source, @RalphSteinhagen FIR/IIR filter generator tool, ...)

Also added a new ImChart-feature that should be useful to cross-check some function w/o having to spin up a full GUI

## ImChart
Compact class for ASCII charting in terminal environments, supporting custom dimensions and styles.

ImChart enables the creation of various graph styles, including bar, braille, and point markers, directly within the terminal. Unicode braille characters are used for compact high-density visualisation, and supports dynamic scaling and some customisation. The primary use-case-focus is for basic visual debugging for library developers for FIR/IIR filter generation, Bode plots, and other basic applications w/o having to spin-up a more complete graphical UI-based solution. Examples:
 
Peek 2023-10-20 11-50

### Features

- Supports various graph styles, including **bar**, **braille**, and **point markers**.
- Utilizes Unicode braille characters for compact, high-density visualisation.
- Offers dynamic scaling and customisation.
- Ideal for developers needing basic visual debugging for library development, such as FIR/IIR filter generation, Bode plots, and other simple applications without requiring a full GUI-based solution.

### Basic Usage

```cpp
ImChart<80, 30> chart;  // use 80 columns x 30 rows
std::vector<double> xValues, sineValuesY, cosineValuesY; // your data
// ... initialise data
chart.draw(xValues, sineValuesY, "sine-like"); // draws a sine-like line
chart.draw(xValues, cosineValuesY, "cosine-like"); // draws a cosine-like line
chart.draw();
```

Example w/ auto-ranging and auto-labelling:
image

### Bar Chart Visualization

Suitable for histograms or similar data representations.

```cpp
auto chart = ImChart<80, 30>({ {0.0, 100.0}, {0.0, 5.0} }); // setting chart boundaries
chart.draw_border = true; // optional border around chart
// ... initialise data
chart.draw<Style::Bars>(xValues, barData, "bar-data");
chart.draw();
```

image

### Individual Point Markers

For detailed point-by-point data representation.

```cpp
auto chart = ImChart<80, 30>(); // setting w/o boundaries -> auto-determined by first dataset
// ... initialise data
chart.draw<Style::Marker>(xValues, pointData, "point-data"); // draws points
chart.draw();
```

image

### Log-Axis Chart

Facilitating logarithmic data visualizations.

```cpp
auto chart = ImChart<120, 16, LogAxisTransform>({ {0.1, 10000.0}, {-100, 0} }); // x-log axis
// ... initialise data
chart.draw(xValues, responseData, "response-data"); // draws the data
chart.draw(); // render the chart
```

image

## Custom Axis Transform

Axes transforms can be extended via:

```cpp
struct MyAxisTransform {
  template<std::floating_point T>
  static std::size_t toScreen(T value, T axisMin, T axisMax, std::size_t screenOffset, std::size_t screenSize);
  template<std::floating_point T>
  static T fromScreen(std::size_t screenCoordinate, T axisMin, T axisMax, std::size_t screenOffset, std::size_t screenSize);
};
double value = 42.0; // or any other value to be transformed
auto screenCoordinate = LinearAxisTransform::toScreen(value, 10., 100., 5, 65);
auto reconstructedValue = LinearAxisTransform::fromScreen(screenCoordinate, 10., 100., 5, 65); // test: reconstructedValue == ~value
```

---

This update seeks to enhance the utility and flexibility developers have when working in terminal environments, expanding both the functionality and accessibility of data visualization tools available during the debugging and development process.

### CODE REVIEW

**Review by drslebedev — APPROVED** [review]
Very impressive, how you did it. It would be very useful for many debug tasks. Very intuitive interface and easy to use. Already played with it a bit for my SignalSources issues. Also in terms of implementation itself very good done! 👍️
I did not find any problem with implementation, need to use it more intensive, for the time being should be approved.

**Comment by RalphSteinhagen** [comment]
@drslebedev thanks for your kind words ... hope this is useful. 

Tried to give my best in terms of a clean- and lean implementation and hope to have found a good compromise. But as you indicated ... the proof is in the pudding and real-world usage.

**Comment by RalphSteinhagen** [comment]
... had to conditionally disable `std::ranges::views::zip` and `std::ranges::contains`  which work locally but not on the CI yet. 

Sorry for the force-push ... hope this builds now also for libc++.

**Comment by RalphSteinhagen** [comment]
@mattkretz needed to add `<algorithm>` prior to including `<vir/simd.h>`  which seems to be missing for the internal `std::clamp(..)` usage by SIMD. Maybe something to add to SIMD directly. This made Emscripten/libc++ not compile

```cpp
[..]/vir-simd-src/vir/simd.h:2244:46: error: no member named 'clamp' in namespace 'std'; did you mean simply 'clamp'?
 2244 |     { return simd<T, A>([&](auto i) { return std::clamp(v[i], lo[i], hi[i]); }); }
      |                                              ^~~~~~~~~~
      |                                              clamp
[..]//vir-simd-src/vir/simd.h:2242:5: note: 'clamp' declared here
 2242 |     clamp(const simd<T, A>& v, const simd<T, A>& lo,
      |     ^
``` 

This is for simd's `GIT_TAG v0.2.0`.

**Comment by RalphSteinhagen** [comment]
Experimented a bit with a more composable `draw(...)` interface that supports drawing multiple data sets and those only using y-values. Here is the [compiler-explorer example](https://compiler-explorer.com/z/Erhfvrhqr) that illustrates what I got so far. Dropping the `Dataset{...}` while keeping it 'clean' and 'lean' was a bit outside of the scope of this PR and 'a bridge to far' for the immediate needs.

Targeted reduced API example (details [here](https://compiler-explorer.com/z/Erhfvrhqr)):
```cpp
ContainerType xValues = {1, 2, 3, 4};
ContainerType yValues1 = {1.1, 1.2, 1.3, 1.4};
ContainerType yValues2 = {2.1, 2.2, 2.3, 2.4};

// original use cases
draw(xValues, yValues1, "DatasetXY");
draw(xValues, yValues1);
draw(yValues1, "DatasetY");

// new multi-dataset API
// how does one get rid of the 'Dataset{...} here 🤔:
draw(Dataset{xValues, yValues1, "Dataset 1"}, Dataset{xValues, yValues2, "Dataset 2"});
draw(Dataset{yValues1, "Dataset 1"}, Dataset{yValues2, "Dataset 2"}); // implicit x-values
    
//i.e.
//draw({xValues, yValues1, "Dataset 1"}, {xValues, yValues2, "Dataset 2"});
//draw({yValues1, "Dataset 1"}, {yValues2, "Dataset 2"}); // implicit x-values
```
Maybe @ivan-cukic, @giucam or @mattkretz may know how to achieve the above w/o code duplication.

*N.B. this may become relevant for the [OpenDigitizer UI](https://github.com/fair-acc/opendigitizer) where we need a safe, clean & lean C++ wrapper for the ImPlot C-style API.*

**Pull request merged**
